Repository ShareEatIt/ShareEatIt-backend, pull requests merged in 2025-01, with the labels that each got.

#203 💫 feat : naver, google, 자체 로그인 /로그아웃 기능 추가
  build.gradle
  src/main/java/com/carpBread/shareEatIt/domain/auth/LoginProvider.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/OAuth2LogoutHandler.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/OAuth2Principal.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/OAuth2UserService.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/controller/LogoutController.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/controller/OAuth2LoginController.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/dto/AuthenticationPrincipal.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/dto/AuthenticationResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/dto/CustomUserDetails.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/dto/OAuth2UserInfo.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/OAuth2Attribute.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/OAuth2LogoutHandler.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/entity/OAuth2Token.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/repository/OAuth2TokenRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/service/OAuth2Service.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/util/JWTFilter.java
  src/main/java/com/carpBread/shareEatIt/domain/auth/util/JWTUtils.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/stompWebSocket/FilterChannelInterceptor.java
  src/main/java/com/carpBread/shareEatIt/domain/member/annotation/CustomEmailValidator.java
  src/main/java/com/carpBread/shareEatIt/domain/member/annotation/Email.java
  src/main/java/com/carpBread/shareEatIt/domain/member/annotation/Password.java
  src/main/java/com/carpBread/shareEatIt/domain/member/annotation/PasswordValidator.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/MemberController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/SentryControllerAdvice.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/SentryTestController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/SignUpController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/request/SignUpRequestDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/AvailResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/LocationResponseDtoComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/LogoutResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberCompletedProfileResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberProfileResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberSharingStatusResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberSharingStatusResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberStickerResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/MemberWithdrawalResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/OpponentInfoResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/SignUpResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/dto/response/StickersResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/member/entity/Member.java
  src/main/java/com/carpBread/shareEatIt/domain/member/repository/MemberRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/member/service/MemberService.java
  src/main/java/com/carpBread/shareEatIt/domain/member/service/SignUpService.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/SharingPostCreateResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/SharingPostResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/map/MapResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/repository/SharingPostRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/service/SharingPostService.java
  src/main/java/com/carpBread/shareEatIt/global/config/PointGeometryFactoryConfig.java
  src/main/java/com/carpBread/shareEatIt/global/config/SecurityConfig.java
  src/main/java/com/carpBread/shareEatIt/global/exception/ErrorCode.java
  src/main/java/com/carpBread/shareEatIt/global/exception/GlobalExceptionHandler.java
  src/test/java/com/carpBread/shareEatIt/config/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/carpBread/shareEatIt/domain/member/controller/MemberControllerTest.java
  src/test/java/com/carpBread/shareEatIt/domain/member/service/MemberServiceTest.java
Labels: feature

#219 ♻️refactor : 중복된 응답 형식 수정
  src/main/java/com/carpBread/shareEatIt/domain/chat/controller/ChatController.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/controller/ChatRoomController.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/service/ChatMessageService.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/service/ChatRoomService.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/stompWebSocket/FilterChannelInterceptor.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/KeywordController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/MemberController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/SignUpController.java
  src/main/java/com/carpBread/shareEatIt/domain/notice/controller/NoticeController.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/controller/GratitudeStickerController.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/controller/ParticipationController.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/repository/ReviewRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/service/GratitudeStickerService.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/service/ParticipationService.java
  src/main/java/com/carpBread/shareEatIt/domain/report/controller/ReportController.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/controller/MapController.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/controller/SharingPostController.java
Labels: refactoring

#226 fix: chat 토큰 인증 과정 수정
  src/main/java/com/carpBread/shareEatIt/domain/chat/stompWebSocket/FilterChannelInterceptor.java
Labels: bug, refactoring
