Repository ShareEatIt/ShareEatIt-backend, pull requests merged in 2025-02, with the labels that each got.

#236 💫 feat : 나눔 통계 기능 추가
  src/main/java/com/carpBread/shareEatIt/domain/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/carpBread/shareEatIt/domain/member/controller/MemberController.java
  src/main/java/com/carpBread/shareEatIt/domain/member/entity/Member.java
  src/main/java/com/carpBread/shareEatIt/domain/member/repository/MemberQuerydslRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/member/repository/MemberQuerydslRepositoryImpl.java
  src/main/java/com/carpBread/shareEatIt/domain/member/service/MemberService.java
  src/main/java/com/carpBread/shareEatIt/domain/member/service/SignUpService.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/controller/SharingPostController.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/controller/SharingPostStatisticsController.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/request/SharingPostListRequestDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/request/SharingPostRequestDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/request/SharingPostUpdateRequestDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/SharingPostCreateResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/SharingPostListResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/SharingPostResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/SharingPostSimpleResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/stats/RankResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/stats/SharingPostPeriodByCategoryResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/stats/SharingPostStatsPeriodResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/dto/response/stats/StatsCategoryPostListSimpleResponseComponent.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/entity/PostStatus.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/entity/SharingPost.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/repository/SharingPostQuerydslRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/repository/SharingPostQuerydslRepositoryImpl.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/repository/SharingPostRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/service/CreateSharingPostService.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/service/SharingPostReadService.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/service/SharingPostService.java
  src/main/java/com/carpBread/shareEatIt/domain/sharingPost/service/StatsService.java
  src/main/java/com/carpBread/shareEatIt/global/entity/Period.java
  src/test/java/com/carpBread/shareEatIt/domain/sharingPost/service/CreateSharingPostServiceTest.java
  src/test/java/com/carpBread/shareEatIt/domain/sharingPost/service/SharingPostReadServiceTest.java
  src/test/java/com/carpBread/shareEatIt/domain/sharingPost/service/SharingPostServiceTest.java
Labels: feature

#237 fix: 참여하기 - 참여기록이 있는 경우 해당 기록 반환, 없는 경우 참여 생성하도록 수정
  gradle.properties
  src/main/java/com/carpBread/shareEatIt/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/chat/stompWebSocket/FilterChannelInterceptor.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/controller/ParticipationController.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/dto/ParticipationResponseDto.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/entity/Participation.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/repository/ParticipationRepository.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/service/GratitudeStickerService.java
  src/main/java/com/carpBread/shareEatIt/domain/participation/service/ParticipationService.java
  src/main/java/com/carpBread/shareEatIt/global/exception/GlobalExceptionHandler.java
Labels: bug

#254 feat: RunTimeException 예외 커스텀
  src/main/java/com/carpBread/shareEatIt/global/exception/GlobalExceptionHandler.java
  src/main/java/com/carpBread/shareEatIt/global/exception/UncheckedExceptionResponseDto.java
Labels: refactoring
